parameters:
#    i_cant_go_user.example.class: ICantGo\UserBundle\Example

services:
#    i_cant_go_user.example:
#        class: %i_cant_go_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
