parameters:
#    i_cant_go_concert.example.class: ICantGo\ConcertBundle\Example

services:
#    i_cant_go_concert.example:
#        class: %i_cant_go_concert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
